name: android-test
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Permission
        run: chmod +x gradlew

      - name: Unit Tests
        run: ./gradlew test