name: "tagged-release"

#on:
#  workflow_run:
#    workflows: ["android-test"]
#    types:
#      - completed
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: "marvinpinto/1.0.5@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
